import type { Metadata } from "next";
import { Space_Grotesk } from "next/font/google"
import { cn } from "@/lib/utils"
import "./globals.css";
import Navbar from "@/components/layout/navbar";

const fontSans = Space_Grotesk({
  subsets: ["latin"],
  variable: "--font-sans",
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased text-neutral-950 bg-white dark",
          fontSans.variable
        )}
      >
        <Navbar/>
        {children}</body>
    </html>
  );
}
